#!/usr/bin/env python3
"""
MetaDataChanger — Strip AI metadata and apply professional EXIF to images.

Modes:
  Camera (default) — looks like a real professional DSLR/mirrorless photo
  Canva  (--canva) — looks like an original export from Canva

Usage:
    python metadatachanger.py photo.jpg
    python metadatachanger.py photo.jpg -c 2 --artist "John Doe"
    python metadatachanger.py design.png --canva --title "Brand Kit 2026" --artist "Jane"
    python metadatachanger.py image.jpg --list-cameras
"""

import argparse
import os
import struct
import sys
import uuid
from datetime import datetime
from pathlib import Path
from xml.sax.saxutils import escape as xml_escape

try:
    from PIL import Image, PngImagePlugin
    import piexif
except ImportError:
    print("[✗] Missing dependencies. Run:  pip install Pillow piexif")
    sys.exit(1)


# ── AI detection ─────────────────────────────────────────────────────────────

AI_KEYWORDS = [
    "stable diffusion", "stablediffusion", "automatic1111", "a1111",
    "comfyui", "comfy", "midjourney", "dall-e", "dall·e", "dalle",
    "adobe firefly", "firefly", "dreamstudio", "novelai", "invokeai",
    "leonardo.ai", "runway", "pika", "kling", "huggingface", "civitai",
    "lora", "dreambooth", "controlnet", "txt2img", "img2img",
    "inpainting", "outpainting", "cfg_scale", "cfg scale",
    "guidance_scale", "negative_prompt", "negative prompt",
    "sampler", "ddim", "euler a", "dpm++", "karras",
    "model hash", "vae hash", "clip skip", "hires fix",
    "denoising strength", "steps:", "seed:", "ai generated",
    "generated by ai", "ai art", "neural network", "diffusion model",
]

AI_PNG_CHUNK_KEYS = {
    "parameters", "prompt", "negative_prompt", "workflow", "comment",
    "model", "seed", "steps", "cfg_scale", "sampler", "scheduler",
    "guidance", "invokeai_metadata", "sd-metadata", "generation_data",
    "comfy_workflow", "dream", "source",
}

# ── Camera presets ────────────────────────────────────────────────────────────

CAMERAS = [
    # (Make, Model, LensModel, FocalLength_mm, FNumber_x10, ISO)
    ("Canon",  "Canon EOS R5",         "RF 24-70mm F2.8 L IS USM",   50, 28, 400),
    ("Canon",  "Canon EOS R6 Mark II", "RF 50mm F1.2 L USM",          50, 12, 800),
    ("Nikon",  "NIKON Z 9",            "NIKKOR Z 24-70mm f/2.8 S",    35, 28, 200),
    ("Nikon",  "NIKON Z 8",            "NIKKOR Z 85mm f/1.8 S",       85, 18, 640),
    ("Sony",   "ILCE-7RM5",            "FE 24-70mm F2.8 GM II",       35, 28, 320),
    ("Sony",   "ILCE-1",               "FE 85mm F1.4 GM",             85, 14, 500),
]

# ── XMP helpers ───────────────────────────────────────────────────────────────

XMP_JPEG_NAMESPACE = b"http://ns.adobe.com/xap/1.0/\x00"


def _canva_xmp(title: str, artist: str, mime: str) -> str:
    now = datetime.now()
    date_iso = now.strftime("%Y-%m-%dT%H:%M:%S+00:00")
    doc_id  = f"xmp.did:canva-{uuid.uuid4()}"
    inst_id = f"xmp.iid:canva-{uuid.uuid4()}"

    # XML-escape user-supplied strings to avoid breaking the XMP packet
    safe_title  = xml_escape(title)  if title  else ""
    safe_artist = xml_escape(artist) if artist else ""

    creator_el = (
        f"   <dc:creator><rdf:Seq><rdf:li>{safe_artist}</rdf:li></rdf:Seq></dc:creator>\n"
        if artist else ""
    )
    title_el = (
        f'   <dc:title><rdf:Alt><rdf:li xml:lang="x-default">{safe_title}</rdf:li>'
        f"</rdf:Alt></dc:title>\n"
        if title else ""
    )

    return (
        '<?xpacket begin="﻿" id="W5M0MpCehiHzreSzNTczkc9d"?>\n'
        '<x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="Adobe XMP Core 9.1">\n'
        ' <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">\n'
        '  <rdf:Description rdf:about=""\n'
        '    xmlns:xmp="http://ns.adobe.com/xap/1.0/"\n'
        '    xmlns:dc="http://purl.org/dc/elements/1.1/"\n'
        '    xmlns:xmpMM="http://ns.adobe.com/xap/1.0/mm/">\n'
        f"   <xmp:CreatorTool>Canva</xmp:CreatorTool>\n"
        f"   <xmp:CreateDate>{date_iso}</xmp:CreateDate>\n"
        f"   <xmp:ModifyDate>{date_iso}</xmp:ModifyDate>\n"
        f"   <xmp:MetadataDate>{date_iso}</xmp:MetadataDate>\n"
        f"   <dc:format>{mime}</dc:format>\n"
        f"{title_el}"
        f"{creator_el}"
        f"   <xmpMM:DocumentID>{doc_id}</xmpMM:DocumentID>\n"
        f"   <xmpMM:InstanceID>{inst_id}</xmpMM:InstanceID>\n"
        "  </rdf:Description>\n"
        " </rdf:RDF>\n"
        "</x:xmpmeta>\n"
        "<?xpacket end=\"w\"?>"
    )


def _inject_xmp_jpeg(path: Path, xmp_string: str) -> None:
    """Insert an XMP APP1 segment into a JPEG file after the EXIF APP1."""
    with open(path, "rb") as f:
        data = f.read()

    if not data.startswith(b"\xff\xd8"):
        return

    payload = XMP_JPEG_NAMESPACE + xmp_string.encode("utf-8")
    seg = b"\xff\xe1" + struct.pack(">H", len(payload) + 2) + payload

    insert_pos = 2
    pos = 2
    while pos + 4 <= len(data):
        marker = data[pos:pos + 2]
        seg_len = struct.unpack(">H", data[pos + 2:pos + 4])[0]

        # Per JPEG spec, segment length must be at least 2 (length itself).
        # Guard against malformed files that would loop forever.
        if seg_len < 2:
            break

        if marker == b"\xff\xe0":  # APP0 JFIF
            insert_pos = pos + 2 + seg_len
        elif marker == b"\xff\xe1":  # APP1
            chunk_start = pos + 4
            if data[chunk_start:chunk_start + 6] == b"Exif\x00\x00":
                insert_pos = pos + 2 + seg_len  # insert right after EXIF
            elif data[chunk_start:chunk_start + len(XMP_JPEG_NAMESPACE)] == XMP_JPEG_NAMESPACE:
                # Replace existing XMP segment
                data = data[:pos] + seg + data[pos + 2 + seg_len:]
                with open(path, "wb") as f:
                    f.write(data)
                return
            break
        else:
            break

        pos += 2 + seg_len

    data = data[:insert_pos] + seg + data[insert_pos:]
    with open(path, "wb") as f:
        f.write(data)


# ── Detection ─────────────────────────────────────────────────────────────────

def detect_ai_traces(image: Image.Image, exif_dict: dict) -> list[str]:
    found = []

    for key, value in image.info.items():
        key_lower = key.lower().strip()
        if key_lower in AI_PNG_CHUNK_KEYS:
            preview = str(value).replace("\n", " ")[:90]
            found.append(f"PNG chunk '{key}': \"{preview}{'...' if len(str(value)) > 90 else ''}\"")
            continue
        if isinstance(value, str):
            val_lower = value.lower()
            for kw in AI_KEYWORDS:
                if kw in val_lower:
                    preview = value.replace("\n", " ")[:90]
                    found.append(f"PNG chunk '{key}' contains '{kw}': \"{preview}...\"")
                    break

    if exif_dict:
        for ifd_name in ("0th", "Exif", "1st"):
            for tag, value in exif_dict.get(ifd_name, {}).items():
                if isinstance(value, bytes):
                    try:
                        value = value.decode("utf-8", errors="ignore").strip()
                    except Exception:
                        continue
                if not isinstance(value, str) or not value:
                    continue
                val_lower = value.lower()
                for kw in AI_KEYWORDS:
                    if kw in val_lower:
                        tag_name = piexif.TAGS.get(ifd_name, {}).get(tag, {}).get("name", str(tag))
                        found.append(f"EXIF {ifd_name}/{tag_name}: \"{value[:90]}\"")
                        break

    xmp_raw = image.info.get("xmp") or image.info.get("XML:com.adobe.xmp", b"")
    xmp_str = (xmp_raw.decode("utf-8", errors="ignore") if isinstance(xmp_raw, bytes) else str(xmp_raw)).lower()
    for kw in ["midjourney", "dall-e", "firefly", "diffusion", "comfyui", "novelai", "ai generated"]:
        if kw in xmp_str:
            found.append(f"XMP data contains AI keyword '{kw}'")

    if "c2pa" in image.info or b"c2pa" in image.info.get("raw", b""):
        found.append("C2PA provenance block detected (AI content authenticity manifest)")

    return found


# ── EXIF builders ─────────────────────────────────────────────────────────────

def build_camera_exif(camera_index: int, artist: str, copyright_str: str) -> bytes:
    make, model, lens, focal, fnum, iso = CAMERAS[camera_index % len(CAMERAS)]
    now = datetime.now()
    date_str = now.strftime("%Y:%m:%d %H:%M:%S").encode()

    zeroth = {
        piexif.ImageIFD.Make:             make.encode(),
        piexif.ImageIFD.Model:            model.encode(),
        piexif.ImageIFD.Software:         b"Adobe Lightroom Classic 13.3",
        piexif.ImageIFD.DateTime:         date_str,
        piexif.ImageIFD.Artist:           artist.encode(),
        piexif.ImageIFD.Copyright:        (copyright_str or f"© {now.year} {artist}").strip().encode(),
        piexif.ImageIFD.XResolution:      (300, 1),
        piexif.ImageIFD.YResolution:      (300, 1),
        piexif.ImageIFD.ResolutionUnit:   2,
        piexif.ImageIFD.ImageDescription: b"",
        piexif.ImageIFD.Orientation:      1,
    }
    exif_ifd = {
        piexif.ExifIFD.DateTimeOriginal:  date_str,
        piexif.ExifIFD.DateTimeDigitized: date_str,
        piexif.ExifIFD.LensModel:         lens.encode(),
        piexif.ExifIFD.ISOSpeedRatings:   iso,
        piexif.ExifIFD.FNumber:           (fnum, 10),
        piexif.ExifIFD.ExposureTime:      (1, 500),
        piexif.ExifIFD.FocalLength:       (focal, 1),
        piexif.ExifIFD.ExposureProgram:   3,
        piexif.ExifIFD.MeteringMode:      5,
        piexif.ExifIFD.Flash:             16,
        piexif.ExifIFD.ColorSpace:        1,
        piexif.ExifIFD.WhiteBalance:      0,
        piexif.ExifIFD.SceneCaptureType:  0,
        piexif.ExifIFD.ExposureMode:      0,
        piexif.ExifIFD.Sharpness:         1,
        piexif.ExifIFD.Saturation:        0,
        piexif.ExifIFD.Contrast:          0,
    }
    return piexif.dump({"0th": zeroth, "Exif": exif_ifd, "GPS": {}, "1st": {}})


def build_canva_exif(artist: str, copyright_str: str) -> bytes:
    now = datetime.now()
    date_str = now.strftime("%Y:%m:%d %H:%M:%S").encode()

    zeroth = {
        piexif.ImageIFD.Software:         b"Canva",
        piexif.ImageIFD.DateTime:         date_str,
        piexif.ImageIFD.Artist:           artist.encode(),
        piexif.ImageIFD.Copyright:        (copyright_str or f"© {now.year} {artist}").strip().encode(),
        piexif.ImageIFD.XResolution:      (96, 1),
        piexif.ImageIFD.YResolution:      (96, 1),
        piexif.ImageIFD.ResolutionUnit:   2,
        piexif.ImageIFD.ImageDescription: b"",
        piexif.ImageIFD.Orientation:      1,
    }
    exif_ifd = {
        piexif.ExifIFD.DateTimeOriginal:  date_str,
        piexif.ExifIFD.DateTimeDigitized: date_str,
        piexif.ExifIFD.ColorSpace:        1,
    }
    return piexif.dump({"0th": zeroth, "Exif": exif_ifd, "GPS": {}, "1st": {}})


# ── Core processing ───────────────────────────────────────────────────────────

def process(
    input_path: str,
    output_path: str,
    canva_mode: bool = False,
    camera_index: int = 0,
    artist: str = "",
    title: str = "",
    copyright_str: str = "",
) -> None:

    src = Path(input_path)
    dst = Path(output_path)
    # Use OUTPUT extension to decide the target format. If the user supplied no
    # extension on -o, fall back to the input extension so the output still
    # matches the source.
    ext = (dst.suffix or src.suffix).lower()

    print(f"\n[→] Processing: {src.name}  ({'Canva mode' if canva_mode else 'Camera mode'})")

    image = Image.open(src)

    exif_dict: dict = {}
    try:
        raw = image.info.get("exif")
        if raw:
            exif_dict = piexif.load(raw)
    except Exception:
        pass

    # 1. Detect
    traces = detect_ai_traces(image, exif_dict)
    if traces:
        print(f"\n[!] AI traces found ({len(traces)}):")
        for t in traces:
            print(f"    - {t}")
    else:
        print("\n[i] No AI traces detected.")

    # 2. Strip — copy image, then wipe the info dict.
    # Using copy() preserves mode, palette (for P-mode PNGs), and all pixel
    # data. Clearing info removes every PNG text chunk, XMP, EXIF, etc.
    icc_profile = image.info.get("icc_profile")  # color-managed images
    clean = image.copy()
    clean.info.clear()

    # JPEG can't store alpha or palette — flatten onto white if needed.
    if ext in (".jpg", ".jpeg") and clean.mode in ("RGBA", "LA", "P", "PA"):
        if clean.mode in ("P", "PA"):
            clean = clean.convert("RGBA")
        if clean.mode in ("RGBA", "LA"):
            bg = Image.new("RGB", clean.size, (255, 255, 255))
            bg.paste(clean, mask=clean.split()[-1])
            clean = bg

    # 3. Build EXIF
    if canva_mode:
        new_exif = build_canva_exif(artist, copyright_str)
    else:
        new_exif = build_camera_exif(camera_index, artist, copyright_str)

    # 4. Save
    save_kwargs: dict = {"exif": new_exif}
    if icc_profile:
        save_kwargs["icc_profile"] = icc_profile

    if ext == ".png":
        save_kwargs["format"] = "PNG"
        if canva_mode:
            pnginfo = PngImagePlugin.PngInfo()
            pnginfo.add_itxt("XML:com.adobe.xmp", _canva_xmp(title, artist, "image/png"))
            save_kwargs["pnginfo"] = pnginfo
        clean.save(dst, **save_kwargs)

    elif ext in (".jpg", ".jpeg"):
        save_kwargs.update({"format": "JPEG", "quality": 95, "subsampling": 0})
        clean.save(dst, **save_kwargs)
        if canva_mode:
            _inject_xmp_jpeg(dst, _canva_xmp(title, artist, "image/jpeg"))

    elif ext == ".webp":
        save_kwargs.update({"format": "WEBP", "quality": 95})
        if canva_mode:
            save_kwargs["xmp"] = _canva_xmp(title, artist, "image/webp").encode("utf-8")
        clean.save(dst, **save_kwargs)

    elif ext == ".tiff":
        save_kwargs["format"] = "TIFF"
        clean.save(dst, **save_kwargs)

    else:
        print(f"[!] Format '{ext}' has limited support — saving as JPEG.")
        dst = dst.with_suffix(".jpg")
        save_kwargs.update({"format": "JPEG", "quality": 95})
        clean.save(dst, **save_kwargs)
        if canva_mode:
            _inject_xmp_jpeg(dst, _canva_xmp(title, artist, "image/jpeg"))

    # 5. Report
    now = datetime.now()
    print(f"\n[✓] AI metadata stripped")
    print(f"[✓] Metadata applied:")
    if canva_mode:
        print(f"    Source    : Canva (export)")
        print(f"    Software  : Canva")
        print(f"    Date      : {now.strftime('%Y-%m-%d  %H:%M:%S')}")
        print(f"    Resolution: 96 DPI  |  sRGB")
        if title:
            print(f"    Title     : {title}")
        if artist:
            print(f"    Creator   : {artist}")
        print(f"    XMP       : CreatorTool=Canva, DocumentID embedded")
    else:
        make, model, lens, focal, fnum, iso = CAMERAS[camera_index % len(CAMERAS)]
        print(f"    Camera    : {model}")
        print(f"    Lens      : {lens}")
        print(f"    Date      : {now.strftime('%Y-%m-%d  %H:%M:%S')}")
        print(f"    ISO       : {iso}  |  f/{fnum/10:.1f}  |  1/500s  |  {focal}mm")
        if artist:
            print(f"    Artist    : {artist}")
    print(f"[✓] Saved → {dst}\n")


# ── CLI ───────────────────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(
        description=(
            "Strip AI metadata and apply professional EXIF.\n"
            "Default: camera mode (DSLR/mirrorless EXIF)\n"
            "--canva: looks like an original Canva design export"
        ),
        formatter_class=argparse.RawTextHelpFormatter,
    )
    parser.add_argument("input", nargs="?", help="Input image path")
    parser.add_argument("-o", "--output",
                        help="Output path (default: <name>_clean.<ext>)")

    # Mode
    parser.add_argument("--canva", action="store_true",
                        help="Apply Canva-style metadata instead of camera EXIF")

    # Camera options (ignored in --canva mode)
    parser.add_argument("-c", "--camera", type=int, default=0, metavar="N",
                        help="Camera preset 0-5 (default: 0 = Canon EOS R5)")
    parser.add_argument("--list-cameras", action="store_true",
                        help="List camera presets and exit")

    # Shared
    parser.add_argument("-a", "--artist", default="",
                        help="Artist / photographer / creator name")
    parser.add_argument("-t", "--title", default="",
                        help="Design title (Canva mode only)")
    parser.add_argument("--copyright", default="",
                        help="Custom copyright string")

    args = parser.parse_args()

    if args.list_cameras:
        print("\nAvailable camera presets:\n")
        for i, (make, model, lens, focal, fnum, iso) in enumerate(CAMERAS):
            print(f"  {i}  {model}")
            print(f"     Lens: {lens}  |  {focal}mm  f/{fnum/10:.1f}  ISO {iso}")
        print()
        return

    if not args.input:
        parser.print_help()
        sys.exit(0)

    if not os.path.isfile(args.input):
        print(f"[✗] File not found: {args.input}")
        sys.exit(1)

    if args.output:
        output = args.output
    else:
        p = Path(args.input)
        output = str(p.with_stem(p.stem + "_clean"))

    process(
        input_path=args.input,
        output_path=output,
        canva_mode=args.canva,
        camera_index=args.camera,
        artist=args.artist,
        title=args.title,
        copyright_str=args.copyright,
    )


if __name__ == "__main__":
    main()
